# Application config:

# Port config:
server:
  port: ${APP_PORT:8080}
  servlet:
    context-path: /api
  error:
    include-stacktrace: never

spring:
  application:
    name: projeto_integrador

  # Datasource config:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:eventmaker}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234}
    driver-class-name: "org.postgresql.Driver"
    hikari:
      schema: public

  # JPA config:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: true

  # Flyway config:
  flyway:
    enabled: true
    locations: db/migration
    baseline-on-migrate: true

  # DevTools config:
  devtools:
    restart:
      enabled: false

# JWT Secret Key:
token.key: MTIzNA==